default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: make-lint
        name: Run make lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [ pre-commit ]
